# Add sources to executable/library
target_sources(${PROJECT_NAME} PRIVATE
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/DSP/Src/audio_user_dsp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/Persistence/Src/flash_persistence.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/SW4STM32/startup_stm32f769xx.s"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/Streaming/Src/audio_speaker_node.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/Streaming/Src/audio_usb_nodes.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/Streaming/Src/audio_usb_playback_session.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/Touchscreen/Src/touchscreen.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/Touchscreen/Src/user_lcd.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/USART/Src/usart.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/USB_Device_Audio/Src/usbd_audio.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/USB_Device_Audio/Src/usbd_audio_10_config_descriptors.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/USB_Device_Audio/Src/usbd_audio_if.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/USB_Device_Audio/Src/usbd_conf.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/USB_Device_Audio/Src/usbd_core_ex.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/USB_Device_Audio/Src/usbd_ctlreq.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/USB_Device_Audio/Src/usbd_desc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/USB_Device_Audio/Src/usbd_ioreq.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Src/main.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Src/stm32f7xx_hal_msp.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Src/stm32f7xx_it.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Src/system_stm32f7xx.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/BSP/Components/adv7533/adv7533.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/BSP/Components/ft6x06/ft6x06.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/BSP/Components/otm8009a/otm8009a.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/BSP/Components/wm8994/Src/wm8994_ex.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/BSP/STM32F769I-Discovery/Src/stm32f769i_discovery.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/BSP/STM32F769I-Discovery/Src/stm32f769i_discovery_audio_ex.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/BSP/STM32F769I-Discovery/Src/stm32f769i_discovery_lcd.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/BSP/STM32F769I-Discovery/Src/stm32f769i_discovery_sdram.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/BSP/STM32F769I-Discovery/Src/stm32f769i_discovery_ts.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/Legacy/stm32f7xx_hal_can.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dfsdm.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.c"
)

configure_file("${CMAKE_CURRENT_SOURCE_DIR}/STM32F769NIHx_FLASH.ld" "${CMAKE_CURRENT_BINARY_DIR}" COPYONLY)

set_target_properties(${PROJECT_NAME} PROPERTIES LINK_DEPENDS "${CMAKE_CURRENT_BINARY_DIR}/STM32F769NIHx_FLASH.ld")
