# DO NOT EDIT THIS FILE --- This file is a managed file, do not edit it directly.

set_target_properties(${PROJECT_NAME} PROPERTIES SUFFIX ".elf")

target_compile_options(${PROJECT_NAME} PUBLIC
    ${CPU_FLAGS}
    ${CC_SECURE}
    # Compiler flags specific to Debug build type
    $<$<CONFIG:Debug>:
      $<$<COMPILE_LANGUAGE:C>: 
        --specs=nano.specs
        -std=gnu11
        -g3
        -Ofast
        -Wall
        -fstack-usage
        -fcyclomatic-complexity
      >
      $<$<COMPILE_LANGUAGE:CXX>: 
        --specs=nano.specs
        -std=gnu++14
        -g3
        -Os
        -fno-use-cxa-atexit
        -Wall
        -fstack-usage
        -fcyclomatic-complexity
      >

      $<$<COMPILE_LANGUAGE:ASM>: 
        --specs=nano.specs
        -g3
        -x
        assembler-with-cpp
      >
    >

)

target_include_directories(${PROJECT_NAME} PUBLIC 
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F7xx_HAL_Driver/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/BSP/Components/wm8994/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/BSP/Components/common"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/BSP/Components"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/Streaming/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/Touchscreen/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/USB_Device_Audio/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/DSP/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/User/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Utilities/Fonts"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/CMSIS/Include"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/CMSIS/Device/ST/STM32F7xx/Include"
    "${CMAKE_CURRENT_SOURCE_DIR}/Drivers/BSP/STM32F769I-Discovery/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/USART/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Application/Persistence/Inc"
)

target_compile_definitions(${PROJECT_NAME} PUBLIC 
    # Symbols specific to Debug build type
    $<$<CONFIG:Debug>: 
      $<$<COMPILE_LANGUAGE:C>: 
        USE_HAL_DRIVER
        STM32F769xx
        USE_STM32F769I_DISCO
        USE_IOEXPANDER
        USE_USB_FS
        USE_USB_FS_INTO_HS
        USE_USB_AUDIO_PLAYBACK=1
      >

      $<$<COMPILE_LANGUAGE:CXX>: 
        USE_HAL_DRIVER
        STM32F769xx
        USE_STM32F769I_DISCO
        USE_IOEXPANDER
        USE_USB_FS
        USE_USB_FS_INTO_HS
        USE_USB_AUDIO_PLAYBACK=1
      >
    >

    
)

target_link_options(${PROJECT_NAME} PUBLIC 
    ${CPU_FLAGS}
    ${CC_SECURE}

    # Linker flags specific to Debug build type
    $<$<CONFIG:Debug>: 
        --specs=nano.specs
        -T${CMAKE_CURRENT_BINARY_DIR}/STM32F769NIHx_FLASH.ld
        --specs=nosys.specs
        -Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/horoscope.map
        -static
        
    >

)
# Clean .map file
set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/build/${CMAKE_BUILD_TYPE}/${PROJECT_NAME}.map")
